---
spring:
  config:
    activate:
      on-profile: local-dev

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true

---
spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery:8761/eureka
    enabled: true
