spring:
  application:
    name: edge
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb:http://USER
          predicates:
            - Path=/microservice-app/user/**
          filters:
            - RewritePath=/microservice-app/(?<segment>.*), /$\{segment}
        - id: order
          uri: lb:http://ORDER
          predicates:
            - Path=/microservice-app/order/**
          filters:
            - RewritePath=/microservice-app/(?<segment>.*), /$\{segment}


server:
  port: 8123

logging:
  level:
    com.codespacelab: DEBUG
    org.springframework.web: DEBUG
    com.netflix: DEBUG